// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `generate_inner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

/// Generate a complete bead pattern from image bytes + a palette JSON string.
///
/// The M8 boundary is `width` / `height` only. The bridge:
/// 1. `load_palette(palette_json.as_bytes())` — `load_palette` takes `&[u8]`, so
///    the JSON `String` is passed as its UTF-8 bytes,
/// 2. builds `GenerateOptions { width, height, ..Default::default() }` — the
///    **exact** construction the CLI uses (filter/cell_size/shape/matcher =
///    engine default Lanczos3/10/Square/Oklab),
/// 3. calls `generate_pattern`, then `pattern_json` on the result.
///
/// On any failure the `BeadError` is flattened to its `Display` string at the
/// boundary (`.to_string()`) and returned as `Err(String)`; FRB raises it as a
/// Dart exception. Structured `BeadError` never crosses — its `PaletteParse`
/// (`serde_json::Error`) / `ImageDecode` / `ImageEncode` (`::image::ImageError`)
/// payloads are external types FRB cannot marshal (D-Errors).
Future<GenerateOutput> generate(
        {required List<int> imageBytes,
        required String paletteJson,
        required int width,
        required int height}) =>
    BeadFfi.instance.api.crateApiGenerate(
        imageBytes: imageBytes,
        paletteJson: paletteJson,
        width: width,
        height: height);

/// FRB mirror of [`bead_core::BeadPattern`]. Fields mirror the real type
/// (`width` / `height` / `cells`) — see `bead-core/src/models/mod.rs`.
class BeadPattern {
  final int width;
  final int height;
  final Uint16List cells;

  const BeadPattern({
    required this.width,
    required this.height,
    required this.cells,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ cells.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BeadPattern &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          cells == other.cells;
}

/// FRB mirror of [`bead_core::ColorStat`]. Fields mirror the real type
/// (`code` / `name` / `count`).
class ColorStat {
  final String code;
  final String name;
  final int count;

  const ColorStat({
    required this.code,
    required this.name,
    required this.count,
  });

  @override
  int get hashCode => code.hashCode ^ name.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColorStat &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          name == other.name &&
          count == other.count;
}

/// The structured result handed back to Dart for one generation call.
///
/// This is bead-ffi's own boundary DTO (not a core type): `GenerateResult` is
/// deliberately non-`Clone` and FRB cannot mirror-move a non-`Clone` owner
/// field-by-field through a single mirror, so the bridge function destructures
/// the owned `GenerateResult` and reassembles its fields here. `pattern` /
/// `stats` ride across as the mirrored structured types (not JSON strings);
/// `pattern_json` is the separately-serialized `pattern.json` body for M9
/// persistence (Dart must not hand-assemble it — D-Output).
class GenerateOutput {
  /// The color-matched pattern (mirrored `BeadPattern`).
  final BeadPattern pattern;

  /// Per-color statistics (mirrored `ColorStat` list).
  final List<ColorStat> stats;

  /// The directly-copyable INIT "Summary Format" text.
  final String summary;

  /// The palette's `brand` label.
  final String brand;

  /// Rendered preview PNG bytes.
  final Uint8List previewPng;

  /// Rendered grid PNG bytes.
  final Uint8List gridPng;

  /// The serialized `pattern.json` body (byte-identical to the CLI's).
  final String patternJson;

  const GenerateOutput({
    required this.pattern,
    required this.stats,
    required this.summary,
    required this.brand,
    required this.previewPng,
    required this.gridPng,
    required this.patternJson,
  });

  @override
  int get hashCode =>
      pattern.hashCode ^
      stats.hashCode ^
      summary.hashCode ^
      brand.hashCode ^
      previewPng.hashCode ^
      gridPng.hashCode ^
      patternJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerateOutput &&
          runtimeType == other.runtimeType &&
          pattern == other.pattern &&
          stats == other.stats &&
          summary == other.summary &&
          brand == other.brand &&
          previewPng == other.previewPng &&
          gridPng == other.gridPng &&
          patternJson == other.patternJson;
}
