// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class BeadFfiApiImplPlatform extends BaseApiImpl<BeadFfiWire> {
  BeadFfiApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BeadPattern dco_decode_bead_pattern(dynamic raw);

  @protected
  ColorStat dco_decode_color_stat(dynamic raw);

  @protected
  GenerateOutput dco_decode_generate_output(dynamic raw);

  @protected
  List<ColorStat> dco_decode_list_color_stat(dynamic raw);

  @protected
  Uint16List dco_decode_list_prim_u_16_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BeadPattern sse_decode_bead_pattern(SseDeserializer deserializer);

  @protected
  ColorStat sse_decode_color_stat(SseDeserializer deserializer);

  @protected
  GenerateOutput sse_decode_generate_output(SseDeserializer deserializer);

  @protected
  List<ColorStat> sse_decode_list_color_stat(SseDeserializer deserializer);

  @protected
  Uint16List sse_decode_list_prim_u_16_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bead_pattern(BeadPattern self, SseSerializer serializer);

  @protected
  void sse_encode_color_stat(ColorStat self, SseSerializer serializer);

  @protected
  void sse_encode_generate_output(
      GenerateOutput self, SseSerializer serializer);

  @protected
  void sse_encode_list_color_stat(
      List<ColorStat> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_16_strict(
      Uint16List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class BeadFfiWire implements BaseWire {
  BeadFfiWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external BeadFfiWasmModule get wasmModule;

@JS()
@anonymous
extension type BeadFfiWasmModule._(JSObject _) implements JSObject {}
